### ISSUE TITLE
Cant not build ParaViewWeb project!

### ISSUE THREAD

**Issue by SohailButt** [Kitware/paraviewweb#521] opened 2020-09-25 12:14 UTC
Getting Following Errors after npm run build

ERROR in ./src/index.js (./node_modules/babel-loader/lib??ref--5-0!./node_modules/eslint-loader??ref--15!./src/index.js)
Module Error (from ./node_modules/eslint-loader/index.js):

C:\paraviewweb\src\index.js
   1:8   error  Unable to resolve path to module 'normalize.css'  import/no-unresolved
  22:35  error  Insert `⏎`                                        prettier/prettier

✖ 2 problems (2 errors, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

 @ ./src/index.js-exposed 1:41-198

ERROR in ./src/index.js (./node_modules/babel-loader/lib??ref--5-0!./node_modules/eslint-loader??ref--15!./src/index.js)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "@babel/preset-env" relative to directory "C:\\paraviewweb"
    at C:\paraviewweb\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\paraviewweb\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\paraviewweb\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\paraviewweb\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\paraviewweb\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\paraviewweb\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\paraviewweb\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\paraviewweb\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\paraviewweb\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\paraviewweb\node_modules\babel-loader\lib\index.js:173:20)
 @ ./src/index.js-exposed 1:41-198

Its really frustrating that even following guideline from ParaviewWeb its not getting loaded.

Please Help!

**Comment by jourdain** [comment] 2020-09-25 14:47
The issue is related to a newer version of `kw-web-suite` compare to what pvw is expecting. Just stick with version `8.0.0` and you should be good.

`npm install kw-web-suite` => `npm install kw-web-suite@8.0.0`

Also what are you trying to do with pvw? In some way it is a deprecated code base and the key components required to do remote visualization are now available in `vtk.js`.

**Comment by SohailButt** [comment] 2020-09-27 17:57
Hi  there,

Thanks for your response Sir. I want to run files from ensight gold format.
And I have installed the version of kw-web-suite@8.0.0 but its giving me
the same error message.

And it also says something about the loader.

ERROR in
./src/React/CollapsibleControls/CollapsibleControlFactory/QueryDataModelWidget.js
9:4
Module parse failed: Unexpected token (9:4)
You may need an appropriate loader to handle this file type.
|   'QueryDataModelWidget',
|   ({ queryDataModel, handleExploration }) => (
>     <QueryDataModelControl
|       key="QueryDataModel"
|       handleExploration={!!handleExploration}
 @ ./src/Rendering/Image/BinaryDataProberImageBuilder/index.js 8:0-91
 @ ./src/Rendering/Image/index.js
 @ ./src/Rendering/index.js
 @ ./src/index.js
 @ ./src/index.js-exposed



Something like this. Its the issue of loader to me. But please do throw
some light on this matter.

Many Thanks

**Comment by jourdain** [comment] 2020-09-28 19:13
I don't see why you need the ParaViewWeb (Web components) project to load your ensight gold format.

**Comment by SohailButt** [comment] 2020-09-29 01:28
Well there is some in between conversion before running ensight gold files
directly on paraviewweb but the main issue is I am still unable to run it
properly on my server.

**Comment by SohailButt** [comment] 2020-09-29 10:29
This is the error I am getting now

> paraviewweb@3.2.13 build:release C:\project\node_modules\paraviewweb
> webpack --mode production

C:\project\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

Error: Cannot find module
'./node_modules/paraviewweb/config/webpack.loaders.js'
Require stack:
- C:\project\node_modules\paraviewweb\webpack.config.js
- C:\project\node_modules\webpack-cli\bin\convert-argv.js
- C:\project\node_modules\webpack-cli\bin\cli.js
- C:\project\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require
(C:\project\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous>
(C:\project\node_modules\paraviewweb\webpack.config.js:4:15)
    at Module._compile
(C:\project\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require
(C:\project\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS
(C:\project\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig
(C:\project\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at C:\project\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports
(C:\project\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at C:\project\node_modules\webpack-cli\bin\cli.js:241:39
    at Object.parse
(C:\project\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at C:\project\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous>
(C:\project\node_modules\webpack-cli\bin\cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous>
(C:\project\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\project\\node_modules\\paraviewweb\\webpack.config.js',
    'C:\\project\\node_modules\\webpack-cli\\bin\\convert-argv.js',
    'C:\\project\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\project\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! paraviewweb@3.2.13 build:release: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the paraviewweb@3.2.13 build:release script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\webdev\AppData\Roaming\npm-cache\_logs\2020-09-29T10_28_46_325Z-debug.log

**Comment by jourdain** [comment] 2020-09-29 14:56
What do you mean? When you [download ParaView](https://www.paraview.org/download/), it does not work?
Because if that works, you already have ParaViewWeb and you are ready to use it.

You should not clone and build this repo if you are not going to contribute to it. If you want to use it, just bring it as a dependency to your project and manage your project.

**Comment by SohailButt** [comment] 2020-09-29 15:02
Sir I am asking for ParaViewWeb not ParaView

**Comment by jourdain** [comment] 2020-09-29 15:13
Indeed, which highlight the fact that you have no understanding of what you are doing and not listening the guidance we provide to solve your main goal "Loading Ensight gold file using ParaViewWeb".

**Comment by SohailButt** [comment] 2020-09-29 15:59
Sir I am really sorry if you are getting frustrated by my attitude but I am
not doing it on purpose.

You asked me to run this command npm install kw-web-suite => npm install
kw-web-suite@8.0.0 I ran it but was unable to build the project I created.

I am confused because the guide I am following does not end up as intended.

https://kitware.github.io/paraviewweb/docs/setup.html

npm run build:release command does not seem to work.

**Comment by SohailButt** [comment] 2020-09-30 08:27
Hi Sabastian,

Many thanks for your response, which is very helpful. I think there is
something missing in my question which I did not tell you about and I
apologize for that.

I am developing a web based system to view the Ansys Fluent Data in Ensight
Gold Format. It works really well in Paraview Software locally on my PC. We
have generated an in house machine lessioning code, which allows us to
generate CFD data fast. The Ansys Fluent data will be updated every one
minute and I would like to view that on a web based system.

I could not find any documentation, tutorials or examples that explain the
procedure of reading an EnSight Gold Data(CFD Data).

I will be obliged of your favour to help me in this regard.

I am very happy to answer any more questions in this regard.

I am really looking forward to hearing from you soon

Best Regards,
Sohail

**Comment by jourdain** [comment] 2020-09-30 14:21
Kitware could help you in that process but it seems that you will be better suited with a support contract with our office in France or in the US depending on which time zone works best for you.
This is mostly because your questions will soon be more involving and we won't be able to provide a descent answer in a reasonable time that our free community support will allow.

**Comment by lihuaiguang** [comment] 2021-08-31 14:42
Hi, 

I have the problem again when building the v 3.2.1 code?

Msgs as follows:
~2021-paraviewweb % **npm run build:release**   

> paraviewweb@0.0.0-semantically-release build:release
> webpack --progress --mode production

assets by status 0 bytes [cached] 1 asset

ERROR in main
Module not found: Error: Can't resolve 'expose-loader' in '/Users/lihuaiguang/Documents/Python/2021-paraviewweb'
resolve 'expose-loader' in '/Users/lhg/Documents/Python/2021-paraviewweb'
  Parsed request is a module
  using description file: /Users/lhg/Documents/Python/2021-paraviewweb/package.json (relative path: .)
    resolve as module
      looking for modules in /Users/lhg/Documents/Python/2021-paraviewweb/node_modules
        single file module
          using description file: /Users/lhg/Documents/Python/2021-paraviewweb/package.json (relative path: ./node_modules/expose-loader)
            no extension
              /Users/lhg/Documents/Python/2021-paraviewweb/node_modules/expose-loader doesn't exist
            .js
              /Users/lhg/Documents/Python/2021-paraviewweb/node_modules/expose-loader.js doesn't exist
        /Users/lhg/Documents/Python/2021-paraviewweb/node_modules/expose-loader doesn't exist
      /Users/lhg/Documents/Python/node_modules doesn't exist or is not a directory
      /Users/lhg/Documents/node_modules doesn't exist or is not a directory
      looking for modules in /Users/lhg/node_modules
        single file module
          using description file: /Users/lhg/package.json (relative path: ./node_modules/expose-loader)
            no extension
              /Users/lhg/node_modules/expose-loader doesn't exist
            .js
              /Users/lhg/node_modules/expose-loader.js doesn't exist
        /Users/lhg/node_modules/expose-loader doesn't exist
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.50.0 compiled with 1 error in 180 ms
`

**Comment by jourdain** [comment] 2021-08-31 15:14
Did you run `npm install`? Also you may want to pull the latest version `3.2.21`.

**Comment by jourdain** [comment] 2021-08-31 15:14
Webpack 5 is not compatible with 3.2.1 but it is with 3.2.21

**Comment by lihuaiguang** [comment] 2021-08-31 23:20
Soryy, the version is 3.2.21, and I have run `npm install`. 
However, I have the msgs in previous post.

**Comment by lihuaiguang** [comment] 2021-08-31 23:33
Did the building require a 'expose-loader.js'?

**Comment by jourdain** [comment] 2021-08-31 23:48
This [line](https://github.com/Kitware/paraviewweb/blob/master/package.json#L39) should bring expose loader...
BTW, why are you trying to build paraviewweb yourself?

**Comment by jourdain** [comment] 2021-08-31 23:51
The ci build ParaViewWeb without issue, closing...

**Closed by jourdain** 2021-08-31 23:51 UTC

**Comment by lihuaiguang** [comment] 2021-09-01 00:03
Thank you, Sebastien. I am developing a online visualizing tool of CFD data.

**Comment by jourdain** [comment] 2021-09-01 00:07
Why don't you bring paraviewweb as a dependency rather than building it? Also, paraviewweb is kind of deprecated and any new Web Viz project we develop/start, we just use vtk.js directly even when dealing with remote rendering.

**Comment by lihuaiguang** [comment] 2021-09-01 03:45
I will, Sebastien. But I don't know if paraviewweb can handle all the input data format?  Because the paraview still have some problem in reading 'ANSYS .inp' files. 
Thanks.

**Comment by jourdain** [comment] 2021-09-01 14:21
ParaViewWeb is ParaView with a web front end. So if ParaView is not a fit for you, ParaView Web won't do better.

**Comment by jourdain** [comment] 2021-09-02 14:17
Because vtk.js is the way forward while enabling more capabilities since all the server part is included within ParaView itself.
